config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => "user_registrations"}

  resources :products do
    resources :comments
  end
  resources :users

  get '/static_pages/landing_page'

  get 'static_pages/featured'

  get 'static_pages/calendar'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  root 'static_pages#about'

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :payments, only: [:index, :show, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments
  validates :name, presence: true

def average_rating
 comments.average(:rating).to_f
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  # GET /products
  # GET /products.json
 def index
 if params[:q]
   search_term = params[:q]
   @products = Product.where("name ilike ?", "%#{search_term}%")
 else
   @products = Product.all
   respond_with @products
 end
 end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end
  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to "/static_pages/landing_page", notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @products }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
    end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
  <div class="row">
    <hr>
    <p>
      <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
      <% if signed_in? && current_user.admin? %>
      <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </p>
    <div class="rated" data-score="<%= comment.rating %>"></div>
    <p><%= "Rating: #{comment.rating}/5" %></p>
    <p><%= comment.body %></p>
  </div>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
<% if @product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
  <ul>
    <% @product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="col-md-12">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
<h4>Add a review:</h4>
<%= form_for([@product, @product.comments.build], remote: true) do |f| %>
<p>
  <%= f.label :body, "Comments" %><br>
  <%= f.text_area :body %>
</p>
<p>
<div class="rating"></div>
</p>
<p>
  <%= submit_tag("Submit") %>
</p>
<% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-md-12">
  <% cache product do %>
  <h3><%= product.name %></h3>
  <%= image_tag(product.image_url, class: "img-responsive") %>
  <p><%= product.description %></p>
  <p><%= product.price %></p>
  <p><%= product.colour %></p>
  <hr>
  <div id="product-links">
    <button type="button" class="btn btn-info-outline">
    <%= link_to 'Show', product %>
    </button>
    <button type="button" class="btn btn-info-outline">
    <%= link_to 'Edit', edit_product_path(product) %>
    </button>
    <button type="button" class="btn btn-info-outline">
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    </button>
    <hr>
  </div>
  <!--/links-->
  <% end %>
</div>
<!-- /col -->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p><%= notice %></p>
<h1>
  <div id="page-layout" class="img-responsive">Merch</div>
</h1>
<div id="container" class="img-responsive">
  <div class "row">
    <% cache(cache_key_for_products) do %>
    <%= render @products %>
    <br>
    <%= link_to 'New Product', new_product_path %>
    <% end %>
  </div>
  <!-- /row -->
</div>
<!-- /container -->

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="show">
<% cache @product do %>
  <div class="row">
    <div class="col-xs-12">
      <div class="thumbnail">
        <!--<%= image_tag @product.image_url, width: "300", class: "img-zoom", id: "zoom_01", data: { :"zoom-image" => @product.image_url } %> -->
        <%= image_tag @product.image_url, width: "300", class: "img-zoom", id: "zoom_01", data: { :"zoom-image" => "http://www.placehold.it/900x900" } %>
        <div class="caption">
          <h3><%= @product.name %></h3>
          <p><%= @product.description %></p>
          <p><%= @product.colour %></p>
          <p><%= @product.price %><p>
          <div class="rated" data-score="<%= @product.average_rating %>"></div>
          <%= form_tag('/payments') do %>
            <%= hidden_field_tag(:product_id, @product.id) %>
            <%= render partial: "shared/stripe_checkout_button" %>
          <% end %>
          <%= render 'new_comment' %>
          <%= render 'comments' %>
          <%= will_paginate @comments %>
        </div>
      </div>
    </div>
  </div>
<% end %>
  <h5>
    <a><span class="glyphicon glyphicon-comment"></span></a>
  </h5>

</div>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>