config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => "user_registrations"}

  resources :products do
    resources :comments
  end
  resources :users

  get '/static_pages/landing_page'

  get 'static_pages/featured'

  get 'static_pages/calendar'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  root 'static_pages#about'

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :payments, only: [:index, :show, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <title>Newtown Radio</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    </link>
    <link rel="stylesheet" href="/assets/stylesheets/custom.css">
    </link>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
<!-- Single button -->
  <body ng-app="shop">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid" id="navbar-style">
      <div class="navbar-form pull-left">
        <%= form_tag("/products", method: "get") do %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
        <% end %>
      </div>
      <div class="navbar-header pull-right">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "About", static_pages_about_path %></li>
          <li><%= link_to "Blog", static_pages_featured_path %></li>
          <li><%= link_to "Store", products_path %></li>
          <li>
            <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
            <%= link_to('Login', new_user_session_path) %>
            <% end %>
          </li>
        </ul>
      </div>
      <!-- end nav collapse -->
    </nav>
    <!-- end navbar -->
    <div class="spacing">
      <% if alert %>
      <p id="alert" class="alert alert-info"><%= alert %></p>
      <% end %>
      <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
      <% end %>
      <%= yield %>
      <div class="col-sm-12">
        <footer>
        <br>
          <p>&copy; 2016</p>
          <p>All Rights Reserved.</p>
        <br>
        </footer>
      </div>
    </div>
  </body>
</html>